import { Duty } from "@prisma/client";

export const others: Duty[] = [
  {
    dutyNumber: "881113A",
    bNL: "TAD",
    bNT: "08:45",
    bFT: "16:45",
    bFL: "TAD",
    duration: "07:30",
    remarks: "Local Training Day",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881103",
    bNL: "HUH",
    bNT: "08:45",
    bFT: "16:45",
    bFL: "HUH",
    duration: "07:30",
    remarks: "EAL EMU Refresher Course",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881111A",
    bNL: "TAD",
    bNT: "08:45",
    bFT: "16:45",
    bFL: "TAD",
    duration: "07:30",
    remarks: "EAL E-Train Refresher Course",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881004A",
    bNL: "TAD",
    bNT: "08:45",
    bFT: "17:00",
    bFL: "TAD",
    duration: "07:15",
    remarks: "Mandatory Basic Safety Training",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881000",
    bNL: "TAD",
    bNT: "08:45",
    bFT: "16:45",
    bFL: "TAD",
    duration: "07:00",
    remarks: "EAL Train Captain Course",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881011",
    bNL: "HUH",
    bNT: "08:30",
    bFT: "16:30",
    bFL: "HUH",
    duration: "07:30",
    remarks: "EMU Driving Practical Training (Empty Train)",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881012",
    bNL: "HUH",
    bNT: "16:45",
    bFT: "00:15",
    bFL: "HUH",
    duration: "07:00",
    remarks: "EMU Driving Practical Training (Empty Train)",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881077A",
    bNL: "TAD",
    bNT: "08:45",
    bFT: "12:15",
    bFL: "TAD",
    duration: "03:30",
    remarks:
      "Mandartory Basic Safty Training Revaliation (摰蝬澈隤脩) 撣哨撣嗅﹦銵憟喳鈭航鋆",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881077B",
    bNL: "TAD",
    bNT: "13:30",
    bFT: "17:00",
    bFL: "TAD",
    duration: "03:30",
    remarks:
      "Mandartory Basic Safty Training Revaliation (摰蝬澈隤脩) 撣哨撣嗅﹦銵憟喳鈭航鋆",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881001",
    bNL: "HUH",
    bNT: "09:00",
    bFT: "16:30",
    bFL: "HUH",
    duration: "07:00",
    remarks: "Week End Programme / Road Familiariztation",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881007",
    bNL: "HUH",
    bNT: "09:00",
    bFT: "16:30",
    bFL: "HUH",
    duration: "07:00",
    remarks: "Qualification Exam for EMU",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881125A",
    bNL: "HUH",
    bNT: "23:00",
    bFT: "06:00",
    bFL: "HUH",
    duration: "07:00",
    remarks: "EMU Test Run - overnight * Operating Training",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881030",
    bNL: "HUH",
    bNT: "08:45",
    bFT: "23:59",
    bFL: "HUH",
    duration: "07:00",
    remarks: "EMU Driving Practical Training (Involved DE/DL)",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881110",
    bNL: "HTD",
    bNT: "08:30",
    bFT: "16:00",
    bFL: "HTD",
    duration: "07:00",
    remarks: "EMU Defect Handling Stock Training",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881166A",
    bNL: "TAD",
    bNT: "08:45",
    bFT: "16:45",
    bFL: "TAD",
    duration: "07:00",
    remarks: "TCI Refresher Course",
    timetableToc: "Training",
  },
  {
    dutyNumber: "881031A",
    bNL: "FTRH",
    bNT: "09:00",
    bFT: "17:00",
    bFL: "FTRH",
    duration: "07:00",
    remarks: "ISDP",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882107A",
    bNL: "HUH",
    bNT: "09:00",
    bFT: "16:30",
    bFL: "HUH",
    duration: "07:00",
    remarks: "Caring Program",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882101A",
    bNL: "HUH",
    bNT: "08:30",
    bFT: "16:00",
    bFL: "HUH",
    duration: "07:00",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882101B",
    bNL: "HUH",
    bNT: "08:30",
    bFT: "16:00",
    bFL: "HUH",
    duration: "07:00",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882102A",
    bNL: "HUH",
    bNT: "05:15",
    bFT: "12:45",
    bFL: "HUH",
    duration: "07:00",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882103A",
    bNL: "LOW",
    bNT: "16:30",
    bFT: "00:30",
    bFL: "HTD",
    duration: "07:30",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882103B",
    bNL: "LOW",
    bNT: "16:30",
    bFT: "00:30",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882104A",
    bNL: "HTD",
    bNT: "16:30",
    bFT: "00:45",
    bFL: "HUH",
    duration: "07:45",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882104B",
    bNL: "HTD",
    bNT: "16:30",
    bFT: "00:45",
    bFL: "HUH",
    duration: "07:45",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882105A",
    bNL: "HUH",
    bNT: "15:15",
    bFT: "23:15",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "882105B",
    bNL: "HUH",
    bNT: "15:15",
    bFT: "23:15",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Intensive Programme",
    timetableToc: "Training",
  },
  {
    dutyNumber: "991104",
    bNL: "HUH",
    bNT: "22:30",
    bFT: "06:00",
    bFL: "HUH",
    duration: "07:00",
    remarks: "撌亦頠/頛潛",
    timetableToc: "Special",
  },
  {
    dutyNumber: "991105",
    bNL: "HUH",
    bNT: "22:45",
    bFT: "06:15",
    bFL: "HUH",
    duration: "07:00",
    remarks: "EMU/LOW 蝧",
    timetableToc: "Special",
  },
  {
    dutyNumber: "991106",
    bNL: "HUH",
    bNT: "22:30",
    bFT: "06:00",
    bFL: "HUH",
    duration: "07:00",
    remarks: "EMU/LOW 蝧/頛潛",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992207A",
    bNL: "HUH",
    bNT: "22:30",
    bFT: "06:00",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Night Time Test Run (1152B)",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992045B",
    bNL: "HUH",
    bNT: "07:00",
    bFT: "15:00",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Spare Duty for New Timetable Support",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992045C",
    bNL: "HUH",
    bNT: "11:30",
    bFT: "19:30",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Spare Duty for New Timetable Support",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992045D",
    bNL: "HUH",
    bNT: "14:00",
    bFT: "22:00",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Spare Duty for New Timetable Support",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992045E",
    bNL: "HUH",
    bNT: "16:30",
    bFT: "00:30",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Spare Duty for New Timetable Support",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992045F",
    bNL: "HTD",
    bNT: "05:00",
    bFT: "13:00",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Spare Duty for New Timetable Support",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992045G",
    bNL: "HUH",
    bNT: "08:45",
    bFT: "16:45",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Spare Duty for New Timetable Support",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992045H",
    bNL: "HUH",
    bNT: "12:00",
    bFT: "20:00",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Spare Duty for New Timetable Support",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992045N",
    bNL: "HUH",
    bNT: "22:00",
    bFT: "06:00",
    bFL: "HUH",
    duration: "07:30",
    remarks: "Spare Duty for New Timetable Support",
    timetableToc: "Special",
  },
  {
    dutyNumber: "992104A",
    bNL: "HUH",
    bNT: "23:00",
    bFT: "06:00",
    bFL: "HUH",
    duration: "07:00",
    remarks: "EMU Test Run -overnight",
    timetableToc: "Special",
  },
  {
    dutyNumber: "991105C",
    bNL: "HTD",
    bNT: "09:30",
    bFT: "16:00",
    bFL: "HTD",
    duration: "06:00",
    remarks: "EMU Test Run - Daytmie",
    timetableToc: "Special",
  },
  {
    dutyNumber: "990004A",
    bNL: "HUH",
    bNT: "07:15",
    bFT: "14:45",
    bFL: "HUH",
    duration: "07:00",
    remarks: "Follow Up",
    timetableToc: "Special",
  },
  {
    dutyNumber: "990023C",
    bNL: "HUH",
    bNT: "22:30",
    bFT: "05:30",
    bFL: "HUH",
    duration: "07:00",
    remarks: "Overnight Joint Exercise",
    timetableToc: "Special",
  },
  {
    dutyNumber: "990006",
    bNL: "HUH",
    bNT: "08:45",
    bFT: "16:45",
    bFL: "HUH",
    duration: "07:00",
    remarks: "SCC Meeting",
    timetableToc: "Special",
  },
  {
    dutyNumber: "990014",
    bNL: "HUH",
    bNT: "08:45",
    bFT: "16:45",
    bFL: "HUH",
    duration: "07:00",
    remarks: "∪極隢株岷",
    timetableToc: "Special",
  },
  {
    dutyNumber: "990007B",
    bNL: "HUH",
    bNT: "09:30",
    bFT: "16:30",
    bFL: "HUH",
    duration: "06:00",
    remarks: "HF Experience Sharing Forum Helper",
    timetableToc: "Special",
  },
  {
    dutyNumber: "990003C",
    bNL: "HUH",
    bNT: "09:30",
    bFT: "17:00",
    bFL: "HUH",
    duration: "07:00",
    remarks: "孵",
    timetableToc: "Special",
  },
];
